# Generated by Django 5.1.5 on 2025-03-14 18:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model_part_num', models.CharField(blank=True, max_length=100)),
                ('quantity_ordered', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True)),
                ('serial_num', models.CharField(blank=True, max_length=100)),
                ('property_num', models.CharField(blank=True, max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'verbose_name': 'Purchase Order Item',
                'verbose_name_plural': 'Purchase Order Items',
                'db_table': 'inventory_purchaseorderitem',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(default='N/A', max_length=50)),
                ('model', models.CharField(default='N/A', max_length=100)),
                ('part_or_unit', models.CharField(choices=[('Part', 'Part'), ('Unit', 'Unit')], default='Part', max_length=5)),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(default='N/A', max_length=50)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.01, max_digits=16, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('use', 'Use')], max_length=6)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changes', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item History',
                'verbose_name_plural': 'Item Histories',
                'db_table': 'inventory_itemhistory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s]+$')])),
                ('model_part_num', models.CharField(blank=True, max_length=100)),
                ('quantity_requested', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', model_utils.fields.StatusField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=100, no_check_for_status=True)),
                ('requested_by', models.ForeignKey(limit_choices_to={'groups__name': 'Technician'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item Request',
                'verbose_name_plural': 'Item Requests',
                'db_table': 'inventory_itemrequest',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order', models.IntegerField(error_messages={'required': 'A Work Order number is required.'})),
                ('datetime_used', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(error_messages={'required': 'An Item is required.'}, on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('used_by', models.ForeignKey(blank=True, limit_choices_to={'groups__name__in': ['Technician', 'Superuser']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Used Item',
                'verbose_name_plural': 'Used Items',
                'db_table': 'inventory_useditem',
                'managed': True,
            },
        ),
    ]
