# Generated by Django 5.1.5 on 2025-03-03 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemhistory',
            options={'managed': True, 'verbose_name': 'Item History', 'verbose_name_plural': 'Item Histories'},
        ),
    ]
