# Generated by Django 5.1.5 on 2025-03-03 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_itemhistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useditem',
            name='item',
            field=models.ForeignKey(error_messages={'required': 'An Item is required.'}, on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='useditem',
            name='work_order',
            field=models.IntegerField(error_messages={'required': 'A Work Order number is required.'}),
        ),
    ]
