# Generated by Django 5.1.5 on 2025-03-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_useditem_item_alter_useditem_work_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemhistory',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('use', 'Use')], max_length=6),
        ),
    ]
