# Generated by Django 5.1.5 on 2025-01-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='part_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
