# Generated by Django 5.2 on 2025-04-25 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_itemrequest_status_changed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
