# Generated by Django 5.1.5 on 2025-03-04 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_itemhistory_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrequest',
            name='item',
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='model_part_num',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=14, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='quantity_requested',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity_ordered',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
