# Generated by Django 5.1.5 on 2025-02-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_item_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='manufacturer',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='model',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
