# Generated by Django 5.1.5 on 2025-02-07 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_item_location_alter_item_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity_min_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
