# Generated by Django 5.1.5 on 2025-02-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_item_quantity_min_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='part_or_unit',
            field=models.CharField(choices=[('Part', 'Part'), ('Unit', 'Unit')], default='Part', max_length=5),
        ),
    ]
