# Generated by Django 5.1.5 on 2025-02-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_itemrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='quantity_min_stock',
            new_name='min_quantity',
        ),
    ]
