# Generated by Django 5.1.5 on 2025-02-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rename_quantity_min_stock_item_min_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='unit_price',
        ),
    ]
