# Generated by Django 5.1.5 on 2025-02-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_item_description_changed_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='modified_by',
            new_name='last_modified_by',
        ),
    ]
