# Generated by Django 5.1.5 on 2025-02-24 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_rename_modified_by_item_last_modified_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('model_part_num', models.CharField(max_length=100)),
                ('quantity_ordered', models.IntegerField()),
                ('description', models.TextField()),
                ('serial_num', models.CharField(max_length=100)),
                ('property_num', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'verbose_name': 'Purchase Order Item',
                'verbose_name_plural': 'Purchase Order Items',
            },
        ),
        migrations.AlterModelOptions(
            name='itemhistory',
            options={'verbose_name': 'Item History'},
        ),
        migrations.AlterModelOptions(
            name='itemrequest',
            options={'verbose_name': 'Item Request', 'verbose_name_plural': 'Item Requests'},
        ),
        migrations.AlterModelOptions(
            name='useditem',
            options={'verbose_name': 'Used Item', 'verbose_name_plural': 'Used Items'},
        ),
    ]
