# Generated by Django 5.1.5 on 2025-02-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_purchaseorderitem_alter_itemhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='model_part_num',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='property_num',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='serial_num',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
