# Generated by Django 5.1.5 on 2025-02-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_purchaseorderitem_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
