# Generated by Django 5.1.5 on 2025-03-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='messgae',
            new_name='message',
        ),
    ]
