# Generated by Django 5.1.5 on 2025-03-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_messgae_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
